### PR TITLE
it is too long!!!

### PR DESCRIPTION
**Pull request by taha-sindi**

### CODE REVIEW

**Comment by Samidahlawi** [comment]
I know, but you don't have to solve it all remember set a timer in your mind for only 2 hours of homework each day and if you did not complete its totally fine! at least you showed effort! however nice work with your codes! keep it up!

**Comment by taha-sindi** [comment]
thank you brother.

‫في الخميس، 25 أبريل 2019 في 11:39 ص تمت كتابة ما يلي بواسطة ‪SamiDahlawi‬‏
<‪notifications@github.com‬‏>:‬

**Comment by Samidahlawi** [comment]
Hey, well done. Keep up the good work 👏. 
Here you can see all the solutions for homework 
https://github.com/wdi-red-coral/hw-week_01-day_04-js-arrays/blob/5d335e5d6aa3c9da03b2a0791dc2c6e7217d8745/homework.js

**Comment by taha-sindi** [comment]
thank you sami you are the best


‫في الاثنين، 29 أبريل 2019 في 3:07 م تمت كتابة ما يلي بواسطة ‪SamiDahlawi‬‏
<‪notifications@github.com‬‏>:‬

**Pull request closed without merging**
